#!/usr/bin/env python3
"""backlog-view: regenerate the read-only BACKLOG dashboard from BACKLOG.md.

Monday-style board, git-native: a derived projection of the single source
(BACKLOG.md) into three glance-able surfaces — "ready & unblocked", a per-owner
grouping, and a Mermaid dependency graph. The generated file is never
hand-edited. `--check` detects a committed dashboard that differs from a fresh
render; the reusable workflow runs it warn-only by default (`enforce: false`,
and lab-os's own caller keeps it false), so a stale dashboard surfaces as a
`::warning` — it blocks a PR only once a caller flips `enforce: true`.

Reuses parse_backlog + parse_deps from backlog_lint (one parser, one
dependency grammar — not copies).

  --backlog PATH   source backlog (default BACKLOG.md)
  --write [PATH]   regenerate the dashboard (default docs/backlog-views.md)
  --check [PATH]   compare the committed dashboard against a fresh render
  --self-test      built-in fixtures

`--check` exit codes are load-bearing (the workflow branches on them):
0 = up to date · 3 = stale (or missing — fails closed) · anything else =
script/parse failure, which the workflow must NOT report as staleness.
A non-empty BACKLOG.md that parses to zero Index rows AND zero Items
(merge-conflict wreckage, truncation, garbage) is a script-failure exit 1,
never exit 3: a destroyed source gets no staleness verdict.

Stdlib only; Python 3.11+.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from backlog_lint import Backlog, _in_ci, parse_backlog, parse_deps  # noqa: E402

_DEFAULT_OUT = "docs/backlog-views.md"
_HEADER = "<!-- generated by scripts/backlog_view.py --write; do not edit by hand -->"
_STALE_EXIT = 3   # distinct from a traceback's exit 1 / a bad-usage exit 2


def render(backlog: Backlog) -> str:
    status = {r["id"]: r["status"] for r in backlog.index}
    title = {r["id"]: r["title"] for r in backlog.index}
    deps = {it.id: parse_deps(it.fields.get("Depends on", "—")) for it in backlog.items}

    out: list[str] = ["# Backlog views", "", _HEADER, ""]
    out.append("_A read-only projection of `BACKLOG.md`. Regenerate: "
               "`python3 scripts/backlog_view.py --write`._")
    out.append("")

    # Ready & unblocked
    out += ["## Ready & unblocked", ""]
    unblocked = [r for r in backlog.index
                 if r["status"] == "ready"
                 and all(status.get(d) == "done" for d in deps.get(r["id"], []))]
    if unblocked:
        out += ["| id | title | owner |", "|---|---|---|"]
        out += [f"| {r['id']} | {r['title']} | {r['owner']} |" for r in unblocked]
    else:
        out.append("_None ready and unblocked right now._")
    out.append("")

    # By owner
    out += ["## By owner", ""]
    owners = sorted({r["owner"] for r in backlog.index}, key=str.lower)
    for o in owners:
        out.append(f"### {o}")
        for r in backlog.index:
            if r["owner"] == o:
                out.append(f"- {r['id']} — {r['title']} ({r['size']}, {r['status']})")
        out.append("")

    # Dependency graph
    out += ["## Dependency graph", ""]
    edges = [(iid, d) for iid, ds in deps.items() for d in ds]
    if edges:
        out.append("```mermaid")
        out.append("graph TD")
        for iid, d in edges:
            out.append(f'  {iid}["{iid}: {title.get(iid, iid)}"] --> {d}')
        out.append("```")
        out.append("")
        out.append("_Edge `A --> B` reads \"A depends on B\"._")
    else:
        out.append("_No dependencies between items._")
    out.append("")

    return "\n".join(out).rstrip() + "\n"


def _write(backlog_path: Path, out_path: Path) -> int:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render(parse_backlog(backlog_path.read_text())))
    print(f"backlog-view: wrote {out_path}")
    return 0


def _check(backlog_path: Path, out_path: Path) -> int:
    """0 = up to date; _STALE_EXIT = stale/missing; 1 = the backlog parsed
    empty (no staleness verdict on a destroyed source). Anything the parse or
    read raises propagates as a normal traceback (exit 1) — a script failure
    must stay distinguishable from staleness, so the workflow never mislabels
    it. Staleness itself is annotated as a ::warning in CI: the workflow owns
    escalation to failure under `enforce`."""
    text = backlog_path.read_text()
    backlog = parse_backlog(text)
    if text.strip() and not backlog.index and not backlog.items:
        # Non-empty text that parses to nothing is a destroyed backlog
        # (conflict markers, truncation, garbage), not an empty one — comparing
        # its render against the committed dashboard would call the wreckage
        # merely "stale". Hard failure, never exit 3.
        msg = f"{backlog_path} parsed empty — refusing staleness verdict"
        print(f"::error::backlog-view: {msg}" if _in_ci() else f"ERROR {msg}")
        return 1
    fresh = render(backlog)
    have = out_path.read_text() if out_path.exists() else ""   # missing = stale (fail closed)
    if fresh == have:
        print(f"backlog-view: {out_path} is up to date")
        return 0
    msg = f"{out_path} is stale; run `python3 scripts/backlog_view.py --write`"
    print(f"::warning::backlog-view: {msg}" if _in_ci() else f"ERROR {msg}")
    return _STALE_EXIT


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Regenerate/check the BACKLOG dashboard.")
    ap.add_argument("--backlog", default="BACKLOG.md")
    ap.add_argument("--write", nargs="?", const=_DEFAULT_OUT, help="regenerate the dashboard")
    ap.add_argument("--check", nargs="?", const=_DEFAULT_OUT,
                    help=f"compare against a fresh render (exit {_STALE_EXIT} if stale)")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args(argv)
    if args.self_test:
        return _self_test()
    if args.write is not None:
        return _write(Path(args.backlog), Path(args.write))
    if args.check is not None:
        return _check(Path(args.backlog), Path(args.check))
    print(render(parse_backlog(Path(args.backlog).read_text())))
    return 0


# The self-test fixture lives at tests/backlog_view/BACKLOG.md — the house
# pattern (cf. tests/log_lint/, tests/merge_bar_check/, tests/docs_budget/):
# a reviewable, diffable file rather than an in-module literal. It is
# lint-valid (zero errors — asserted in the self-test, matching the digest
# fixture's bar): every Item block carries the full template schema, and the
# Index is the byte-exact render of the blocks. B2/B3 differ only in whether
# their dependency is done, which is what exercises the unblocked predicate.
_FIXTURE = Path(__file__).resolve().parent.parent / "tests/backlog_view/BACKLOG.md"


def _fixture() -> str:
    return _FIXTURE.read_text()


def _self_test() -> int:
    ok = True

    def expect(name: str, cond: bool) -> None:
        nonlocal ok
        print(f"  [{'ok' if cond else 'FAIL'}] {name}")
        ok = ok and cond

    fix = _fixture()

    # The fixture must model a real input: backlog_lint accepts it with zero
    # errors (full schema, Index == render of the blocks).
    from backlog_lint import lint, required_fields
    template = Path(__file__).resolve().parent.parent / "templates/backlog-item.template.md"
    expect("fixture is lint-valid (zero errors)",
           not lint(parse_backlog(fix), required_fields(template.read_text())).errors)

    md = render(parse_backlog(fix))
    # B2 is ready and its only dep (B1) is done -> unblocked; B3 depends on B2 (ready) -> blocked.
    ready_section = md.split("## By owner")[0]
    expect("B2 shown ready&unblocked", "| B2 |" in ready_section)
    expect("B3 NOT ready&unblocked (dep not done)", "| B3 |" not in ready_section)
    expect("per-owner has Watson", "### Watson" in md)
    expect("mermaid graph present", "```mermaid" in md and "B2" in md and "-->" in md)
    expect("generated header present", _HEADER in md)

    # The staleness detector is the workflow's whole contract — prove the
    # write -> check round-trip and both exit codes through _write/_check.
    import tempfile
    with tempfile.TemporaryDirectory() as td:
        src = Path(td) / "BACKLOG.md"
        out = Path(td) / "views.md"
        src.write_text(fix)
        expect("--write exits 0", _write(src, out) == 0)
        expect("fresh dashboard passes --check (exit 0)", _check(src, out) == 0)
        src.write_text(fix.replace("Ready thing", "Renamed thing"))
        expect(f"stale dashboard fails --check (exit {_STALE_EXIT})",
               _check(src, out) == _STALE_EXIT)
        expect(f"missing dashboard is stale, fails closed (exit {_STALE_EXIT})",
               _check(src, Path(td) / "absent.md") == _STALE_EXIT)
        # A destroyed backlog (non-empty, parses to zero rows AND zero items)
        # gets NO staleness verdict: exit 1 (script-failure lane), never 3.
        garbage = Path(td) / "GARBAGE.md"
        garbage.write_text("<<<<<<< HEAD\ntotal wreckage\n=======\nother side\n"
                           ">>>>>>> theirs\n")
        expect("destroyed backlog refuses staleness verdict (exit 1, not 3)",
               _check(garbage, out) == 1)

    print("backlog-view self-test:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
