#!/usr/bin/env python3
"""backlog-view: regenerate the read-only BACKLOG dashboard from BACKLOG.md.

Monday-style board, git-native: a derived projection of the single source
(BACKLOG.md) into three glance-able surfaces — "ready & unblocked", a per-owner
grouping, and a Mermaid dependency graph. The generated file is never
hand-edited. `--check` detects a committed dashboard that differs from a fresh
render; the reusable workflow runs it warn-only by default (`enforce: false`),
so in a downstream caller a stale dashboard surfaces as a `::warning` until
that caller flips `enforce: true`. lab-os's own caller runs it enforcing
(flipped 2026-08-06, once the committed dashboard first went green).

Reuses parse_backlog + parse_deps from backlog_lint (one parser, one
dependency grammar — not copies).

  --backlog PATH   source backlog (default BACKLOG.md)
  --write [PATH]   regenerate the dashboard (default docs/backlog-views.md)
  --check [PATH]   compare the committed dashboard against a fresh render
  --self-test      built-in fixtures

`--check` exit codes are load-bearing (the workflow branches on them):
0 = up to date · 3 = stale (or missing — fails closed) · anything else =
script/parse failure, which the workflow must NOT report as staleness.
A source that fails integrity — any parse error, a non-empty BACKLOG.md
parsing to zero Item blocks (merge-conflict wreckage, or truncation that
leaves only the Index), or Index rows drifting from the Item blocks — is a
script-failure exit 1, never exit 3: a broken source gets no staleness
verdict, and `--write` refuses to render a dashboard from it.

`source_integrity_errors` and `ready_unblocked` are defined here and shared
with backlog_digest.py (one copy, not two). Their long-term home is
backlog_lint, beside the parser and dependency grammar they lean on; they
are kept out of it in this branch so PR #68 does not fork PR #67's file.

Stdlib only; Python 3.11+.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from backlog_lint import (  # noqa: E402
    Backlog,
    F_DEPS,
    dep_value_error,
    parse_backlog,
    parse_deps,
    render_index,
)

_DEFAULT_OUT = "docs/backlog-views.md"
_HEADER = "<!-- generated by scripts/backlog_view.py --write; do not edit by hand -->"
_STALE_EXIT = 3   # distinct from a traceback's exit 1 / a bad-usage exit 2


def _in_ci() -> bool:
    """CI annotation gate, defined here (and re-exported to backlog_digest)
    rather than imported from backlog_lint: `_in_ci` is not part of that
    module's documented API and #67 is free to rename it. Owning the check in
    this branch's own file removes the cross-PR private-name dependency the
    #68 review flagged (its long-term home is backlog_lint beside the parser)."""
    import os
    return bool(os.environ.get("GITHUB_ACTIONS"))


def _missing_backlog(backlog_path: Path) -> bool:
    """A missing --backlog file: clean one-line error, exit-1 lane — matching
    backlog_digest (the #68 review's align-on-digest suggestion) instead of a
    raw FileNotFoundError traceback. Still the script-failure lane (never the
    staleness exit 3); a genuinely unreadable/undecodable file still raises."""
    if backlog_path.exists():
        return False
    msg = f"{backlog_path} not found"
    print(f"::error::backlog-view: {msg}" if _in_ci() else f"ERROR {msg}")
    return True


def source_integrity_errors(backlog: Backlog) -> list[str]:
    """Defects that make any derived rendering unsafe — fail closed on all.

    Shared by backlog_view and backlog_digest (see module docstring for the
    backlog_lint seam). Three classes, any one of which refuses a render:
    - parse errors: the parser saw structure it could not attach;
    - a non-empty source parsing to zero Item blocks (merge-conflict
      wreckage, or truncation that leaves only the Index — a disjunction
      with the parse-error class, since a clean truncation after the Index
      produces no parse error at all);
    - Index rows and Item blocks drifting apart. Two sub-classes, both here:
      (a) an id present on one side only — the renderers read
      status/owner/size/title from the Index and dependencies from the Item
      blocks, so an id-set mismatch would otherwise be treated as
      dependency-free ("fails open"); (b) a row whose id MATCHES but whose
      status/owner/size/title CELL disagrees with its Item block — the exact
      drift class the docstring named but the id-set check missed, so a stale
      cell (Index `ready`, block `in-progress`) shipped a confidently-wrong
      dashboard that `--check` passed. Both are caught by reusing
      backlog-lint's byte-exact Index check (the committed Index must equal
      render_index(items)); that check runs warn-only until its enforce flip,
      so this guard cannot wait on that wiring and owns the comparison itself.
    """
    errs = [f"parse error: {e}" for e in backlog.parse_errors]
    if backlog.raw.strip() and not backlog.items:
        errs.append("non-empty backlog parsed to zero Item blocks "
                    "(truncated or destroyed source)")
    idx = {r["id"] for r in backlog.index}
    blk = {it.id for it in backlog.items}
    if idx - blk:
        errs.append("Index rows with no Item block: " + ", ".join(sorted(idx - blk)))
    if blk - idx:
        errs.append("Item blocks with no Index row: " + ", ".join(sorted(blk - idx)))
    # Cell-content drift (Blocker B): the id-set checks above catch a row/block
    # present on ONE side only, but NOT a row whose id matches while its
    # status/owner/size/title CELL disagrees with the Item block. The renderers
    # read exactly those cells FROM the Index, so a stale cell renders wrong
    # data and `--check` passes on it. Reuse #67's byte-exact Index compare so
    # any cell drift refuses the render, the same way lint's own stale-Index
    # error does. Gate on matching id-sets / clean parse / non-empty items so
    # this line reports ONLY the new content class — the row-count, zero-item,
    # and parse classes already carry their own messages above.
    if idx == blk and backlog.items and not backlog.parse_errors:
        committed = backlog.index_table
        rendered = render_index(backlog.items).splitlines()
        if committed != rendered:
            detail = next(
                (f"committed {c!r} vs rendered-from-items {r!r}"
                 for c, r in zip(committed, rendered) if c != r),
                "the committed Index table shape differs from the render")
            errs.append("Index cell drift vs Item blocks — the dashboard would "
                        f"render stale data: {detail}")
    # `Depends on` fail-open (Watson's two #68 blockers, one root): the byte-
    # exact Index compare above validates title/owner/size/status (all emitted
    # by render_index), but `Depends on` is read ONLY from the Item blocks and
    # never appears in the Index — so nothing above can see it. A value that
    # parse_deps silently reads as [] (a deleted line, prose like "blocked on
    # Watson", a lowercase `b2`) let ready_unblocked list a genuinely-blocked
    # item as "ready & unblocked". Validate every item's value with the shared
    # grammar check (#67's dep_value_error) and fail closed — a missing field
    # or an unreadable value refuses the render, so a blocked item can never
    # advertise as ready. lint() runs the same check; view/digest cannot wait
    # on lint's enforce flip, so this guard owns it. (Missing is a hard error
    # here even though lint catches it via the required-field check — the view
    # path does not run that check.)
    for it in backlog.items:
        if F_DEPS not in it.fields:
            errs.append(f"{it.id}: missing '{F_DEPS}' field")
            continue
        dep_err = dep_value_error(it.fields[F_DEPS])
        if dep_err:
            errs.append(f"{it.id}: {dep_err}")
    return errs


def ready_unblocked(backlog: Backlog) -> list[dict[str, str]]:
    """Index rows with status `ready` whose every dependency is `done`.

    The one copy of the predicate for both renderers (backlog_digest imports
    it). Deliberately indexes `deps[...]` instead of `.get(..., [])`: after
    the source-integrity guard every Index row has an Item block, and a
    bypassed guard must surface as a KeyError in the script-failure lane —
    never as "this item has no dependencies"."""
    status = {r["id"]: r["status"] for r in backlog.index}
    deps = {it.id: parse_deps(it.fields.get("Depends on", "—")) for it in backlog.items}
    return [r for r in backlog.index
            if r["status"] == "ready"
            and all(status.get(d) == "done" for d in deps[r["id"]])]


def _refuse(backlog_path: Path, backlog: Backlog, verdict: str) -> bool:
    """Print every integrity error and return True if the render must not
    happen. Exit-1 lane by contract: the workflow hard-fails it even in
    warn-only mode, and the printed remedy never says `--write` (writing a
    dashboard rendered from a broken source is the failure mode this
    guard exists to prevent)."""
    errs = source_integrity_errors(backlog)
    if not errs:
        return False
    for e in errs:
        print(f"::error::backlog-view: {backlog_path}: {e}" if _in_ci()
              else f"ERROR {backlog_path}: {e}")
    msg = f"{backlog_path} failed source integrity — refusing {verdict}"
    print(f"::error::backlog-view: {msg}" if _in_ci() else f"ERROR {msg}")
    return True


def _md_cell(v: str) -> str:
    """Escape `|` for a Markdown table cell or list line (`\\|` renders as
    `|`) — a raw pipe splits the row into extra cells. Same escape as
    backlog_lint._cell; duplicated here only until the shared helpers move
    to backlog_lint (see module docstring)."""
    return v.replace("|", "\\|")


def _mermaid_label(v: str) -> str:
    """Escape `\"` inside a quoted Mermaid node label with `#quot;` (Mermaid's
    entity escape): a raw quote terminates the label and invalidates the
    whole diagram block on the rendered docs site. Nothing upstream
    constrains titles — backlog_lint accepts any non-blank title text."""
    return v.replace('"', "#quot;")


def render(backlog: Backlog) -> str:
    title = {r["id"]: r["title"] for r in backlog.index}
    deps = {it.id: parse_deps(it.fields.get("Depends on", "—")) for it in backlog.items}

    out: list[str] = ["# Backlog views", "", _HEADER, ""]
    out.append("_A read-only projection of `BACKLOG.md`. Regenerate: "
               "`python3 scripts/backlog_view.py --write`._")
    out.append("")

    # Ready & unblocked
    out += ["## Ready & unblocked", ""]
    unblocked = ready_unblocked(backlog)
    if unblocked:
        out += ["| id | title | owner |", "|---|---|---|"]
        out += [f"| {r['id']} | {_md_cell(r['title'])} | {_md_cell(r['owner'])} |"
                for r in unblocked]
    else:
        out.append("_None ready and unblocked right now._")
    out.append("")

    # By owner
    out += ["## By owner", ""]
    owners = sorted({r["owner"] for r in backlog.index}, key=str.lower)
    for o in owners:
        out.append(f"### {o}")
        for r in backlog.index:
            if r["owner"] == o:
                out.append(f"- {r['id']} — {_md_cell(r['title'])} "
                           f"({r['size']}, {r['status']})")
        out.append("")

    # Dependency graph
    out += ["## Dependency graph", ""]
    edges = [(iid, d) for iid, ds in deps.items() for d in ds]
    if edges:
        out.append("```mermaid")
        out.append("graph TD")
        for iid, d in edges:
            label = _mermaid_label(f"{iid}: {title.get(iid, iid)}")
            out.append(f'  {iid}["{label}"] --> {d}')
        out.append("```")
        out.append("")
        out.append("_Edge `A --> B` reads \"A depends on B\"._")
    else:
        out.append("_No dependencies between items._")
    out.append("")

    return "\n".join(out).rstrip() + "\n"


def _write(backlog_path: Path, out_path: Path) -> int:
    if _missing_backlog(backlog_path):
        return 1
    backlog = parse_backlog(backlog_path.read_text(encoding="utf-8"))
    if _refuse(backlog_path, backlog, "to write a dashboard rendered from it"):
        return 1
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render(backlog), encoding="utf-8")
    print(f"backlog-view: wrote {out_path}")
    return 0


def _check(backlog_path: Path, out_path: Path) -> int:
    """0 = up to date; _STALE_EXIT = stale/missing; 1 = the backlog failed
    source integrity (parse errors, zero Item blocks from non-empty text, or
    Index/Item drift — no staleness verdict on a broken source). A missing
    --backlog file is a clean one-line exit-1 error (aligned with digest); any
    other read/parse failure still propagates as a traceback (exit 1) — a
    script failure must stay distinguishable from staleness, so the workflow
    never mislabels it. Staleness itself is annotated as a ::warning in CI: the
    workflow owns escalation to failure under `enforce`."""
    if _missing_backlog(backlog_path):
        return 1
    backlog = parse_backlog(backlog_path.read_text(encoding="utf-8"))
    if _refuse(backlog_path, backlog, "staleness verdict"):
        # Comparing a broken source's render against the committed dashboard
        # would call the wreckage merely "stale" — and the stale-path remedy
        # tells the author to run `--write`. Hard failure, never exit 3.
        return 1
    fresh = render(backlog)
    have = out_path.read_text(encoding="utf-8") if out_path.exists() else ""   # missing = stale (fail closed)
    if fresh == have:
        print(f"backlog-view: {out_path} is up to date")
        return 0
    msg = f"{out_path} is stale; run `python3 scripts/backlog_view.py --write`"
    print(f"::warning::backlog-view: {msg}" if _in_ci() else f"ERROR {msg}")
    return _STALE_EXIT


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Regenerate/check the BACKLOG dashboard.")
    ap.add_argument("--backlog", default="BACKLOG.md")
    ap.add_argument("--write", nargs="?", const=_DEFAULT_OUT, help="regenerate the dashboard")
    ap.add_argument("--check", nargs="?", const=_DEFAULT_OUT,
                    help=f"compare against a fresh render (exit {_STALE_EXIT} if stale)")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args(argv)
    if args.self_test:
        return _self_test()
    if args.write is not None:
        return _write(Path(args.backlog), Path(args.write))
    if args.check is not None:
        return _check(Path(args.backlog), Path(args.check))
    if _missing_backlog(Path(args.backlog)):
        return 1
    backlog = parse_backlog(Path(args.backlog).read_text(encoding="utf-8"))
    if _refuse(Path(args.backlog), backlog, "a render"):
        return 1
    print(render(backlog))
    return 0


# The self-test fixture lives at tests/backlog_view/BACKLOG.md — the house
# pattern (cf. tests/log_lint/, tests/merge_bar_check/, tests/docs_budget/):
# a reviewable, diffable file rather than an in-module literal. It is
# lint-valid (zero errors — asserted in the self-test, matching the digest
# fixture's bar): every Item block carries the full template schema, and the
# Index is the byte-exact render of the blocks. B2/B3 differ only in whether
# their dependency is done, which is what exercises the unblocked predicate.
_FIXTURE = Path(__file__).resolve().parent.parent / "tests/backlog_view/BACKLOG.md"


def _fixture() -> str:
    return _FIXTURE.read_text(encoding="utf-8")


def _self_test() -> int:
    ok = True

    def expect(name: str, cond: bool) -> None:
        nonlocal ok
        print(f"  [{'ok' if cond else 'FAIL'}] {name}")
        ok = ok and cond

    fix = _fixture()

    # The fixture must model a real input: backlog_lint accepts it with zero
    # errors (full schema, Index == render of the blocks).
    from backlog_lint import lint, required_fields
    template = Path(__file__).resolve().parent.parent / "templates/backlog-item.template.md"
    expect("fixture is lint-valid (zero errors)",
           not lint(parse_backlog(fix), required_fields(template.read_text(encoding="utf-8"))).errors)

    md = render(parse_backlog(fix))
    # B2 is ready and its only dep (B1) is done -> unblocked; B3 depends on B2 (ready) -> blocked.
    ready_section = md.split("## By owner")[0]
    expect("B2 shown ready&unblocked", "| B2 |" in ready_section)
    expect("B3 NOT ready&unblocked (dep not done)", "| B3 |" not in ready_section)
    expect("per-owner has Watson", "### Watson" in md)
    expect("mermaid graph present", "```mermaid" in md and "B2" in md and "-->" in md)
    expect("generated header present", _HEADER in md)

    # Defense-in-depth behind the entry-point guard: fed a drifted backlog
    # directly, the predicate must raise into the script-failure lane —
    # never fall open to "this item has no dependencies".
    try:
        ready_unblocked(parse_backlog(fix.split("## B3 —")[0]))
        expect("ready_unblocked raises on drifted input (no fail-open)", False)
    except KeyError:
        expect("ready_unblocked raises on drifted input (no fail-open)", True)

    # Title escaping (Watson review of PR #68, Important 3): the one output
    # defect a well-formed fixture cannot surface. A `"` in a title must not
    # terminate the quoted Mermaid label; a `|` must not split a table cell.
    expect("_md_cell escapes |", _md_cell("a|b") == "a\\|b")
    expect('_mermaid_label escapes "', _mermaid_label('a "b"') == "a #quot;b#quot;")
    quoted = render(parse_backlog(fix.replace("Ready thing", 'Fix the "ready" bar')))
    expect("quoted title survives in the mermaid label",
           'B2["B2: Fix the #quot;ready#quot; bar"] --> B1' in quoted)
    expect("no raw quote left inside a mermaid label",
           '"B2: Fix the "' not in quoted)

    # The staleness detector is the workflow's whole contract — prove the
    # write -> check round-trip and both exit codes through _write/_check.
    import tempfile
    with tempfile.TemporaryDirectory() as td:
        src = Path(td) / "BACKLOG.md"
        out = Path(td) / "views.md"
        src.write_text(fix, encoding="utf-8")
        expect("--write exits 0", _write(src, out) == 0)
        expect("fresh dashboard passes --check (exit 0)", _check(src, out) == 0)
        src.write_text(fix.replace("Ready thing", "Renamed thing"), encoding="utf-8")
        expect(f"stale dashboard fails --check (exit {_STALE_EXIT})",
               _check(src, out) == _STALE_EXIT)
        expect(f"missing dashboard is stale, fails closed (exit {_STALE_EXIT})",
               _check(src, Path(td) / "absent.md") == _STALE_EXIT)
        # A destroyed backlog (non-empty, parses to zero rows AND zero items)
        # gets NO staleness verdict: exit 1 (script-failure lane), never 3.
        garbage = Path(td) / "GARBAGE.md"
        garbage.write_text("<<<<<<< HEAD\ntotal wreckage\n=======\nother side\n"
                           ">>>>>>> theirs\n", encoding="utf-8")
        expect("destroyed backlog refuses staleness verdict (exit 1, not 3)",
               _check(garbage, out) == 1)

        # Fail-closed source-integrity guards (Watson review of PR #68: the
        # fail-open Blockers). Each broken source must land in the exit-1
        # script-failure lane — never exit 3, never a silent render.
        import contextlib
        import io

        # A missing --backlog file (not the dashboard): clean exit-1 with a
        # one-line error, aligned with backlog_digest — no FileNotFoundError
        # traceback (#68 review suggestion).
        _mbuf = io.StringIO()
        with contextlib.redirect_stdout(_mbuf):
            _rc_missing = _check(Path(td) / "no-such-backlog.md", out)
        expect("missing --backlog file: clean exit-1, not a traceback",
               _rc_missing == 1 and "not found" in _mbuf.getvalue())

        def check_broken(text: str) -> tuple[int, str]:
            broken = Path(td) / "BROKEN.md"
            broken.write_text(text, encoding="utf-8")
            buf = io.StringIO()
            with contextlib.redirect_stdout(buf):
                rc = _check(broken, out)
            return rc, buf.getvalue()

        # Index row with no Item block (drop B3's block, keep its row): the
        # old predicate treated B3 as dependency-free and listed it as ready
        # & unblocked despite `Depends on: B2` (B2 is ready, not done).
        rc, msg = check_broken(fix.split("## B3 —")[0])
        expect("Index/Item drift refuses verdict (exit 1, not 3)", rc == 1)
        expect("drift message names the drifted id", "B3" in msg)
        # Blocker B (adversarial self-review): CELL-content drift, not just
        # id-set drift. B3's Item block says in-progress; the committed Index
        # row still says ready; ids match. The OLD guard returned [] and the
        # dashboard rendered `ready` (read from the Index) on wrong data —
        # `--check` exit 0 on a confidently-wrong board. The byte-exact Index
        # compare must now refuse. Mutation-check: delete the cell-drift block
        # in source_integrity_errors and this goes green (exit 3).
        cell_drift = fix.replace("- **Depends on:** B2\n- **Status:** ready",
                                 "- **Depends on:** B2\n- **Status:** in-progress")
        rc, msg = check_broken(cell_drift)
        expect("status cell drift refuses verdict (exit 1, not 3)", rc == 1)
        expect("cell-drift message flags the stale render",
               "cell drift" in msg.lower() and "stale data" in msg)
        drifted_bl = parse_backlog(cell_drift)
        expect("cell drift caught though id-sets MATCH (the Blocker-B class)",
               source_integrity_errors(drifted_bl) != []
               and not ({r["id"] for r in drifted_bl.index}
                        ^ {it.id for it in drifted_bl.items}))
        # False-positive guard: a genuinely-consistent Index (the clean
        # fixture) still renders clean — the new check adds no noise.
        expect("consistent Index still passes integrity (no false positive)",
               source_integrity_errors(parse_backlog(fix)) == [])
        # Truncated after the Index (index non-empty, zero Item blocks, zero
        # parse errors): must not escape the guard via the old conjunction.
        rc, _m = check_broken(fix.split("## Items")[0])
        expect("truncated-after-Index refuses verdict (exit 1, not 3)", rc == 1)
        # A parse error (hyphenated item heading) is an integrity failure even
        # though index and surviving items may still look plausible.
        rc, msg = check_broken(fix.replace("## B2 — Ready thing",
                                           "## B2 - Ready thing"))
        expect("parse error refuses verdict (exit 1, not 3)",
               rc == 1 and "parse error" in msg)

        # `Depends on` fail-open (Watson's two #68 blockers): `Depends on` is
        # read only from the Item blocks and never emitted by render_index, so
        # the Index compare above cannot see it. B3 genuinely depends on B2
        # (ready, not done) — a value parse_deps reads as [] made B3 advertise
        # as ready & unblocked. Each malformed value must now refuse the render
        # via the shared source_integrity_errors (exit 1). These mutations keep
        # the Index byte-exact, so ONLY the new dep check fires. Mutation-check:
        # delete the Depends-on validation loop and all three go green (exit 3).
        # (B3's line is unique — B2's is `Depends on: B1`.)
        prose = fix.replace("- **Depends on:** B2\n- **Status:** ready",
                            "- **Depends on:** blocked on Watson\n- **Status:** ready")
        rc, msg = check_broken(prose)
        expect("prose Depends-on refuses verdict (exit 1, names B3)",
               rc == 1 and "B3" in msg and "neither" in msg)
        # "not rendered ready" is enforced by refusing to render at all: the
        # guarded --write path produces no dashboard, so B3 can never reach a
        # committed board advertising as ready. (render() itself is guard-free
        # by design — like ready_unblocked; the entry points own the guard.)
        prose_src, prose_out = Path(td) / "PROSE.md", Path(td) / "prose-views.md"
        prose_src.write_text(prose, encoding="utf-8")
        with contextlib.redirect_stdout(io.StringIO()):
            rc = _write(prose_src, prose_out)
        expect("prose Depends-on: --write refuses, no dashboard written",
               rc == 1 and not prose_out.exists())
        rc, msg = check_broken(fix.replace("- **Depends on:** B2\n- **Status:** ready",
                                           "- **Depends on:** b2\n- **Status:** ready"))
        expect("lowercase b2 Depends-on refuses verdict (exit 1)",
               rc == 1 and "B3" in msg)
        rc, msg = check_broken(fix.replace("- **Depends on:** B2\n- **Status:** ready",
                                           "- **Status:** ready"))
        expect("deleted Depends-on line refuses verdict (exit 1, missing field)",
               rc == 1 and "B3" in msg and "missing" in msg)
        # No false positive: a well-formed `Depends on: B2` with B2 done still
        # renders ready & unblocked and passes integrity (B2 dep B1 is done in
        # the fixture — B2 is the well-formed done-dep case). The dep guard adds
        # no noise to a valid backlog.
        expect("well-formed Depends-on (dep done) still renders ready (no false positive)",
               "| B2 |" in render(parse_backlog(fix)).split("## By owner")[0]
               and source_integrity_errors(parse_backlog(fix)) == [])

        # --write refuses the same inputs instead of committing a dashboard
        # rendered from wreckage.
        broken_out = Path(td) / "broken-views.md"
        broken_src = Path(td) / "BROKEN.md"
        broken_src.write_text(fix.split("## Items")[0], encoding="utf-8")
        with contextlib.redirect_stdout(io.StringIO()):
            rc = _write(broken_src, broken_out)
        expect("--write refuses a broken source (exit 1, nothing written)",
               rc == 1 and not broken_out.exists())

    print("backlog-view self-test:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
