#!/usr/bin/env python3
"""backlog-view: regenerate the read-only BACKLOG dashboard from BACKLOG.md.

Monday-style board, git-native: a derived projection of the single source
(BACKLOG.md) into three glance-able surfaces — "ready & unblocked", a per-owner
grouping, and a Mermaid dependency graph. The generated file is never
hand-edited. `--check` detects a committed dashboard that differs from a fresh
render; the reusable workflow runs it warn-only by default (`enforce: false`,
and lab-os's own caller keeps it false), so a stale dashboard surfaces as a
`::warning` — it blocks a PR only once a caller flips `enforce: true`.

Reuses parse_backlog + parse_deps from backlog_lint (one parser, one
dependency grammar — not copies).

  --backlog PATH   source backlog (default BACKLOG.md)
  --write [PATH]   regenerate the dashboard (default docs/backlog-views.md)
  --check [PATH]   compare the committed dashboard against a fresh render
  --self-test      built-in fixtures

`--check` exit codes are load-bearing (the workflow branches on them):
0 = up to date · 3 = stale (or missing — fails closed) · anything else =
script/parse failure, which the workflow must NOT report as staleness.

Stdlib only; Python 3.11+.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from backlog_lint import Backlog, _in_ci, parse_backlog, parse_deps  # noqa: E402

_DEFAULT_OUT = "docs/backlog-views.md"
_HEADER = "<!-- generated by scripts/backlog_view.py --write; do not edit by hand -->"
_STALE_EXIT = 3   # distinct from a traceback's exit 1 / a bad-usage exit 2


def render(backlog: Backlog) -> str:
    status = {r["id"]: r["status"] for r in backlog.index}
    title = {r["id"]: r["title"] for r in backlog.index}
    deps = {it.id: parse_deps(it.fields.get("Depends on", "—")) for it in backlog.items}

    out: list[str] = ["# Backlog views", "", _HEADER, ""]
    out.append("_A read-only projection of `BACKLOG.md`. Regenerate: "
               "`python3 scripts/backlog_view.py --write`._")
    out.append("")

    # Ready & unblocked
    out += ["## Ready & unblocked", ""]
    unblocked = [r for r in backlog.index
                 if r["status"] == "ready"
                 and all(status.get(d) == "done" for d in deps.get(r["id"], []))]
    if unblocked:
        out += ["| id | title | owner |", "|---|---|---|"]
        out += [f"| {r['id']} | {r['title']} | {r['owner']} |" for r in unblocked]
    else:
        out.append("_None ready and unblocked right now._")
    out.append("")

    # By owner
    out += ["## By owner", ""]
    owners = sorted({r["owner"] for r in backlog.index}, key=str.lower)
    for o in owners:
        out.append(f"### {o}")
        for r in backlog.index:
            if r["owner"] == o:
                out.append(f"- {r['id']} — {r['title']} ({r['size']}, {r['status']})")
        out.append("")

    # Dependency graph
    out += ["## Dependency graph", ""]
    edges = [(iid, d) for iid, ds in deps.items() for d in ds]
    if edges:
        out.append("```mermaid")
        out.append("graph TD")
        for iid, d in edges:
            out.append(f'  {iid}["{iid}: {title.get(iid, iid)}"] --> {d}')
        out.append("```")
        out.append("")
        out.append("_Edge `A --> B` reads \"A depends on B\"._")
    else:
        out.append("_No dependencies between items._")
    out.append("")

    return "\n".join(out).rstrip() + "\n"


def _write(backlog_path: Path, out_path: Path) -> int:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render(parse_backlog(backlog_path.read_text())))
    print(f"backlog-view: wrote {out_path}")
    return 0


def _check(backlog_path: Path, out_path: Path) -> int:
    """0 = up to date; _STALE_EXIT = stale/missing. Anything the parse or read
    raises propagates as a normal traceback (exit 1) — a script failure must
    stay distinguishable from staleness, so the workflow never mislabels it."""
    fresh = render(parse_backlog(backlog_path.read_text()))
    have = out_path.read_text() if out_path.exists() else ""   # missing = stale (fail closed)
    if fresh == have:
        print(f"backlog-view: {out_path} is up to date")
        return 0
    msg = f"{out_path} is stale; run `python3 scripts/backlog_view.py --write`"
    print(f"::error::backlog-view: {msg}" if _in_ci() else f"ERROR {msg}")
    return _STALE_EXIT


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Regenerate/check the BACKLOG dashboard.")
    ap.add_argument("--backlog", default="BACKLOG.md")
    ap.add_argument("--write", nargs="?", const=_DEFAULT_OUT, help="regenerate the dashboard")
    ap.add_argument("--check", nargs="?", const=_DEFAULT_OUT,
                    help=f"compare against a fresh render (exit {_STALE_EXIT} if stale)")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args(argv)
    if args.self_test:
        return _self_test()
    if args.write is not None:
        return _write(Path(args.backlog), Path(args.write))
    if args.check is not None:
        return _check(Path(args.backlog), Path(args.check))
    print(render(parse_backlog(Path(args.backlog).read_text())))
    return 0


_FIX = """## Index

| id | title | owner | size | status |
|---|---|---|---|---|
| B1 | Done thing | Kiara | S | done |
| B2 | Ready thing | Watson | M | ready |
| B3 | Blocked thing | Arya | S | ready |

## Items

## B1 — Done thing

- **Depends on:** —
- **Status:** done

## B2 — Ready thing

- **Depends on:** B1
- **Status:** ready

## B3 — Blocked thing

- **Depends on:** B2
- **Status:** ready
"""


def _self_test() -> int:
    ok = True

    def expect(name: str, cond: bool) -> None:
        nonlocal ok
        print(f"  [{'ok' if cond else 'FAIL'}] {name}")
        ok = ok and cond

    md = render(parse_backlog(_FIX))
    # B2 is ready and its only dep (B1) is done -> unblocked; B3 depends on B2 (ready) -> blocked.
    ready_section = md.split("## By owner")[0]
    expect("B2 shown ready&unblocked", "| B2 |" in ready_section)
    expect("B3 NOT ready&unblocked (dep not done)", "| B3 |" not in ready_section)
    expect("per-owner has Watson", "### Watson" in md)
    expect("mermaid graph present", "```mermaid" in md and "B2" in md and "-->" in md)
    expect("generated header present", _HEADER in md)

    # The staleness detector is the workflow's whole contract — prove the
    # write -> check round-trip and both exit codes through _write/_check.
    import tempfile
    with tempfile.TemporaryDirectory() as td:
        src = Path(td) / "BACKLOG.md"
        out = Path(td) / "views.md"
        src.write_text(_FIX)
        expect("--write exits 0", _write(src, out) == 0)
        expect("fresh dashboard passes --check (exit 0)", _check(src, out) == 0)
        src.write_text(_FIX.replace("Ready thing", "Renamed thing"))
        expect(f"stale dashboard fails --check (exit {_STALE_EXIT})",
               _check(src, out) == _STALE_EXIT)
        expect(f"missing dashboard is stale, fails closed (exit {_STALE_EXIT})",
               _check(src, Path(td) / "absent.md") == _STALE_EXIT)

    print("backlog-view self-test:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
